[package]
name = "dghv"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "0.8", features = ["std"] }
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"
num-primes = "0.3"